### ISSUE TITLE
README not ready

### ISSUE THREAD

**Issue by davidbonora** [davidbonora/todo-list#2]
@Cococod3

**Comment by davidbonora** [comment]
Titulo ok @Cococod3

**Comment by GreenOliverJ** [comment]
Tit 2 ok @davidbonora

**Comment by davidbonora** [comment]
Prerreq ok @Cococod3

**Comment by GreenOliverJ** [comment]
Ok installing @davidbonora  he editado tus links, creo que no estaban linkeados.

**Comment by GreenOliverJ** [comment]
pero miralo a ver si me he equivocado

**Comment by davidbonora** [comment]
deployment ok @Cococod3 

y si, lo has arreglado tu porque mi commit no se habia subido, gracias!

**Comment by GreenOliverJ** [comment]
Built with ok @davidbonora

**Comment by davidbonora** [comment]
Authors ok @Cococod3
